### ISSUE TITLE
这个代码里面是png，但是admin里面和注释都是jpg，不太一致

### ISSUE THREAD

**Issue by jemygraw** [eiblog/utils#1]
https://github.com/eiblog/utils/blob/a56f1b5e9c3c7442bb659df1f2e05adccccbbb6a/tmpl/tmplfunc.go#L46

导致了很多困惑

**Comment by deepzz0** [comment]
@jemygraw 抱歉，是没改全

**Comment by deepzz0** [comment]
@jemygraw 已经更新
